connections = 
{
    /abm_and_smem/abm_and_smem_ctl/S_AXI              bdc/sources_1/bd/abm_and_smem/src/abm_and_smem_ctl.v REG 
    /packet_generator/poke/poke_ctl/S_AXI
    /packet_generator/transmit/abm_send_ctl/S_AXI


}
